name: Deploy (Staging)
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

env:
  NODE_ENV: staging
jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_PACKAGE_TOKEN }}
      ECR_REPOSITORY_URL: ${{ secrets.TCG_PLATFORM_STG_ECR_REPOSITORY_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kahnabell
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            kahnabell/sql-migrate
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
